### ISSUE TITLE
'.' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by AmberGoop** [lucasstarsz/Java-Discord-Bot-Template#1]
" '.' is not recognized as an internal or external command, operable program or batch files"
is the only message the command terminal returns when i put "./gradlew clean build" in the console, as told by step 4 of the "building and running" instruction section of the readme.
am i missing a program or something? what did i do wrong here?

**Comment by AmberGoop** [comment]
well, someone else has just told me that, for windows, i have to remove the "./"

**Comment by lucasstarsz** [comment]
My apologies for not seeing this sooner. In most of my Gradle-based projects I make a point to include [a link to this post about issues using the `gradlew` file](https://gist.github.com/lucasstarsz/9bbc306f8655b916367d557043e498ad). I'll make sure to add it to this repository post-haste!
